[package]
authors = ["Alex Eden <alexandereden91@gmail.com>"]
description = "Embedded rust implementation of the Adafruit Seesaw library."
edition = "2021"
license = "MIT/Apache-2.0"
name = "adafruit-seesaw"
readme = "README.md"
version = "0.0.1"

[dependencies]
embedded-hal = "0.2"

[profile.release]
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and they don't increase the size on Flash
lto = true          # better optimizations
incremental = false
opt-level = 's'
