[package]
name = "adafruit-seesaw"
version = "0.2.1"
authors = ["Alex Eden <alexandereden91@gmail.com>"]
edition = "2021"

description = "Platform-agnostic implementation of the Adafruit Seesaw library."
documentation = "https://docs.rs/adafruit-seesaw"
categories = ["embedded", "no-std"]
keywords = ["shared-bus", "seesaw", "adafruit", "i2c", "bus"]
exclude = [".cargo", "memory.x"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/alexeden/adafruit-seesaw"

[package.metadata.docs.rs]
all-features = true

[lib]
bench = false
test = false



[dependencies]
embedded-hal = "0.2"
shared-bus = "0.2"

[dev-dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
rtt-target = { version = "0.3", features = ["cortex-m"] }
stm32f4xx-hal = { features = ["rt", "stm32f405", "sdio"], version = "0.13" }

[profile.release]
codegen-units = 1   # better optimizations
debug = true        # symbols are nice and they don't increase the size on Flash
lto = true          # better optimizations
incremental = false
opt-level = 's'
